/****************************************************************/
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/*                                                              */
/* This file provides an interface between eTPU code and CPU    */
/* code. All references to the PWMF function should be made with*/
/* information in this file. This allows only symbolic          */
/* information to be referenced which allows the eTPU code to be*/
/* optimized without effecting the CPU code.                    */
/****************************************************************/

#ifndef _ETPU_PWMF_AUTO_H_
#define _ETPU_PWMF_AUTO_H_

/****************************************************************
 * Function Configuration Information.
 ****************************************************************/
#define FS_ETPU_PWMF_FUNCTION_NUMBER   2
#define FS_ETPU_PWMF_TABLE_SELECT      0
#define FS_ETPU_PWMF_NUM_PARMS         0x0020

/****************************************************************
 * Host Service Request Definitions.
 ****************************************************************/
#define FS_ETPU_PWMF_UPDATE            1
#define FS_ETPU_PWMF_STOP_LOW          7
#define FS_ETPU_PWMF_STOP_HIGH         6
#define FS_ETPU_PWMF_START             5

/****************************************************************
 * Parameter Definitions.
 ****************************************************************/
#define FS_ETPU_PWMF_DUTY_OFFSET       0x0001
#define FS_ETPU_PWMF_CHANNUM_OFFSET    0x0000
#define FS_ETPU_PWMF_PERIODCOPY_OFFSET 0x0005
#define FS_ETPU_PWMF_OPTIONS_OFFSET    0x0004
#define FS_ETPU_PWMF_DTC_OFFSET        0x0008
#define FS_ETPU_PWMF_ATIME_OFFSET      0x0009
#define FS_ETPU_PWMF_BTIME_OFFSET      0x0011
#define FS_ETPU_PWMF_ACTIME_OFFSET     0x000D
#define FS_ETPU_PWMF_BCTIME_OFFSET     0x0015
#define FS_ETPU_PWMF_FLAGS_OFFSET      0x000C
#endif
