/****************************************************************/
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/*                                                              */
/* This file provides an interface between eTPU code and CPU    */
/* code. All references to the PWMMDC function should be made   */
/* with information in this file. This allows only symbolic     */
/* information to be referenced which allows the eTPU code to be*/
/* optimized without effecting the CPU code.                    */
/****************************************************************/

#ifndef _ETPU_PWMMDC_AUTO_H_
#define _ETPU_PWMMDC_AUTO_H_

/****************************************************************
 * Function Configuration Information.
 ****************************************************************/
#define FS_ETPU_PWMMDC_FUNCTION_NUMBER 1
#define FS_ETPU_PWMMDC_TABLE_SELECT    1
#define FS_ETPU_PWMMDC_NUM_PARMS       0x0080

/****************************************************************
 * Host Service Request Definitions.
 ****************************************************************/
#define FS_ETPU_PWMMDC_INIT_NORMAL     7
#define FS_ETPU_PWMMDC_INIT_HALF_CYCLE 5
#define FS_ETPU_PWMMDC_UPDATE          2

/****************************************************************
 * Parameter Definitions.
 ****************************************************************/
#define FS_ETPU_PWMMDC_PHASES_OFFSET   0x0000
#define FS_ETPU_PWMMDC_STARTOFFSET_OFFSET 0x0001
#define FS_ETPU_PWMMDC_MODULATION_OFFSET 0x0004
#define FS_ETPU_PWMMDC_UPDATETIME_OFFSET 0x0005
#define FS_ETPU_PWMMDC_DEADTIME_OFFSET 0x0009
#define FS_ETPU_PWMMDC_MINPW_OFFSET    0x000D
#define FS_ETPU_PWMMDC_PERIOD_OFFSET   0x0011
#define FS_ETPU_PWMMDC_PERIODCOPY_OFFSET 0x0015
#define FS_ETPU_PWMMDC_EDGETIME_OFFSET 0x0019
#define FS_ETPU_PWMMDC_VOLTAGE_OFFSET  0x001D
#define FS_ETPU_PWMMDC_PHASESSTARTED_OFFSET 0x0008
#define FS_ETPU_PWMMDC_PHASEA_OFFSET   0x0020
#define FS_ETPU_PWMMDC_PHASEB_OFFSET   0x0040
#define FS_ETPU_PWMMDC_PHASEC_OFFSET   0x0060

/****************************************************************
 * Value Definitions.
 ****************************************************************/
#define FS_ETPU_PWMMDC_MODULATION_NO   0
#define FS_ETPU_PWMMDC_MODULATION_UNSIGNED 1
#define FS_ETPU_PWMMDC_MODULATION_SIGNED 2
#define FS_ETPU_PWMMDC_FM_EDGE_ALIGNED 0
#define FS_ETPU_PWMMDC_FM_CENTER_ALIGNED 1
#define FS_ETPU_PWMMDC_FM_SINGLE_CHANNELS 0
#define FS_ETPU_PWMMDC_FM_COMPLEMEN_PAIRS 2
#define FS_ETPU_PWMMDC_OPTION_DUTY_NEG 1
#define FS_ETPU_PWMMDC_OPTION_SWAP     2
#define FS_ETPU_PWMMDC_PHASES_STARTED  1
#endif
