set MATLAB=C:\Program Files\MATLAB\R2011b
"%MATLAB%\bin\win32\gmake" -f two_virtual_wheel_autocode_8.mk  GENERATE_REPORT=1 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=1 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 PORTABLE_WORDSIZES=0 GENERATE_ERT_S_FUNCTION=0
