/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT!
 *
 * This file provides an interface between eTPU code and CPU
 * code. All references to the ASDC function should be made with
 * information in this file. This allows only symbolic
 * information to be referenced which allows the eTPU code to be
 * optimized without effecting the CPU code.
 *****************************************************************/

#ifndef _FS_ETPU_ASDC_AUTO_H_
#define _FS_ETPU_ASDC_AUTO_H_

/****************************************************************
 * Function Configuration Information.
 ****************************************************************/
#define FS_ETPU_ASDC_FUNCTION_NUMBER   8
#define FS_ETPU_ASDC_TABLE_SELECT      0
#define FS_ETPU_ASDC_NUM_PARMS         0x0050

/****************************************************************
 * Host Service Request Definitions.
 ****************************************************************/
#define FS_ASDC_HSR_INIT_HIGH_PERIOD_MODE 7
#define FS_ASDC_HSR_INIT_HIGH_SYNC_MODE 6
#define FS_ASDC_HSR_INIT_LOW_PERIOD_MODE 5
#define FS_ASDC_HSR_INIT_LOW_SYNC_MODE 4
#define FS_ASDC_HSR_MEASURE_DC_OFFSETS 2

/****************************************************************
 * Parameter Definitions.
 ****************************************************************/
#define FS_ETPU_ASDC_MEASURE_TIME_OFFSET 0x000D
#define FS_ETPU_ASDC_PERIOD_OFFSET     0x0001
#define FS_ETPU_ASDC_P_EDGE_TIME_OFFSET 0x0009
#define FS_ETPU_ASDC_START_OFFSET_OFFSET 0x0005
#define FS_ETPU_ASDC_PERIODS_PER_OUTERLOOP_OFFSET 0x0011
#define FS_ETPU_ASDC_OUTERLOOP_CHAN_OFFSET 0x0000
#define FS_ETPU_ASDC_INNERLOOP_CHAN_OFFSET 0x0004
#define FS_ETPU_ASDC_RESULT_QUEUE_OFFSET 0x0015
#define FS_ETPU_ASDC_BIT_SHIFT_OFFSET  0x0019
#define FS_ETPU_ASDC_MEASURE_DC_OFFSET_MASK_OFFSET 0x0010
#define FS_ETPU_ASDC_QUEUE_OFFSET_A_OFFSET 0x0008
#define FS_ETPU_ASDC_QUEUE_OFFSET_B_OFFSET 0x000C
#define FS_ETPU_ASDC_DC_OFFSET_A_OFFSET 0x001D
#define FS_ETPU_ASDC_DC_OFFSET_B_OFFSET 0x0021
#define FS_ETPU_ASDC_FORGET_FACTOR_A_OFFSET 0x0025
#define FS_ETPU_ASDC_FORGET_FACTOR_B_OFFSET 0x0029
#define FS_ETPU_ASDC_OUTPUT_A_OFFSET   0x002D
#define FS_ETPU_ASDC_OUTPUT_B_OFFSET   0x0031
#define FS_ETPU_ASDC_P_OUTPUT_A_OFFSET 0x0035
#define FS_ETPU_ASDC_P_OUTPUT_B_OFFSET 0x0039
#define FS_ETPU_ASDC_MEASURE_SAMPLES_MASK_OFFSET 0x0014
#define FS_ETPU_ASDC_P_SIGN_A_OFFSET   0x003D
#define FS_ETPU_ASDC_P_SIGN_B_OFFSET   0x0041

/****************************************************************
 * Value Definitions.
 ****************************************************************/
#define FS_ETPU_ASDC_FM_SIGNUM_A_OFF   0
#define FS_ETPU_ASDC_FM_SIGNUM_A_ON    1
#define FS_ETPU_ASDC_FM_SIGNUM_B_OFF   0
#define FS_ETPU_ASDC_FM_SIGNUM_B_ON    2
#endif
