/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT!
 *
 * This file provides an interface between eTPU code and CPU
 * code. All references to the SC function should be made with
 * information in this file. This allows only symbolic
 * information to be referenced which allows the eTPU code to be
 * optimized without effecting the CPU code.
 *****************************************************************/

#ifndef _ETPU_SC_AUTO_H_
#define _ETPU_SC_AUTO_H_

/****************************************************************
 * Function Configuration Information.
 ****************************************************************/
#define FS_ETPU_SC_FUNCTION_NUMBER     10
#define FS_ETPU_SC_TABLE_SELECT        0
#define FS_ETPU_SC_NUM_PARMS           0x0058

/****************************************************************
 * Host Service Request Definitions.
 ****************************************************************/
#define FS_ETPU_SC_INIT_HD_MASTER      7
#define FS_ETPU_SC_INIT_HD_SLAVE       6
#define FS_ETPU_SC_INIT_QD_MASTER      5
#define FS_ETPU_SC_INIT_QD_SLAVE       4
#define FS_ETPU_SC_CALC                1

/****************************************************************
 * Parameter Definitions.
 ****************************************************************/
#define FS_ETPU_SC_PERIOD_OFFSET       0x0001
#define FS_ETPU_SC_STARTOFFSET_OFFSET  0x0005
#define FS_ETPU_SC_SERVICESPERIRQ_OFFSET 0x0009
#define FS_ETPU_SC_LINKCHAN_OFFSET     0x0000
#define FS_ETPU_SC_PPID_OFFSET         0x000D
#define FS_ETPU_SC_POUTPUT_OFFSET      0x0011
#define FS_ETPU_SC_OMEGADESIRED_OFFSET 0x0015
#define FS_ETPU_SC_OMEGADESIREDRAMP_OFFSET 0x0019
#define FS_ETPU_SC_RAMPINCRUP_OFFSET   0x001D
#define FS_ETPU_SC_RAMPINCRDOWN_OFFSET 0x0021
#define FS_ETPU_SC_ERROR_OFFSET        0x0025
#define FS_ETPU_SC_OMEGAACTUAL_OFFSET  0x0029
#define FS_ETPU_SC_PHDPERIOD_OFFSET    0x002D
#define FS_ETPU_SC_PHDDIRECTION_OFFSET 0x0031
#define FS_ETPU_SC_MAXHDPERIOD_OFFSET  0x0035
#define FS_ETPU_SC_SCALE_OFFSET        0x0039
#define FS_ETPU_SC_PQDPCSC_OFFSET      0x003D
#define FS_ETPU_SC_PQDTCRVALUE_OFFSET  0x0041
#define FS_ETPU_SC_QDLASTTCR_OFFSET    0x0045
#define FS_ETPU_SC_QDPOSITIONDIFF_OFFSET 0x0049
#define FS_ETPU_SC_QDTIMEDIFF_OFFSET   0x004D

/****************************************************************
 * Value Definitions.
 ****************************************************************/
#define FS_ETPU_SC_FM_PID_OFF          0
#define FS_ETPU_SC_FM_PID_ON           1
#define FS_ETPU_SC_FM_RAMP_OFF         0
#define FS_ETPU_SC_FM_RAMP_ON          2
#endif
