/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT!
 *
 * This file provides an interface between eTPU code and CPU
 * code. All references to the BC function should be made with
 * information in this file. This allows only symbolic
 * information to be referenced which allows the eTPU code to be
 * optimized without effecting the CPU code.
 *****************************************************************/

#ifndef _ETPU_BC_AUTO_H_
#define _ETPU_BC_AUTO_H_

/****************************************************************
 * Function Configuration Information.
 ****************************************************************/
#define FS_ETPU_BC_FUNCTION_NUMBER     11
#define FS_ETPU_BC_TABLE_SELECT        0
#define FS_ETPU_BC_NUM_PARMS           0x0028

/****************************************************************
 * Host Service Request Definitions.
 ****************************************************************/
#define FS_ETPU_BC_INIT_SLAVE_ON_OFF   7
#define FS_ETPU_BC_INIT_SLAVE_PWM      6
#define FS_ETPU_BC_INIT_MASTER_ON_OFF  5
#define FS_ETPU_BC_CALC                1

/****************************************************************
 * Parameter Definitions.
 ****************************************************************/
#define FS_ETPU_BC_PERIOD_OFFSET       0x0001
#define FS_ETPU_BC_STARTOFFSET_OFFSET  0x0005
#define FS_ETPU_BC_SERVICESPERIRQ_OFFSET 0x0009
#define FS_ETPU_BC_UDCBUSMEASURED_OFFSET 0x000D
#define FS_ETPU_BC_UDCBUSON_OFFSET     0x0011
#define FS_ETPU_BC_UDCBUSOFF_OFFSET    0x0015
#define FS_ETPU_BC_PWMSLOPE_OFFSET     0x0019

/****************************************************************
 * FM Definitions.
 ****************************************************************/
#define FS_ETPU_BC_POLARITY_ON_HIGH    0
#define FS_ETPU_BC_POLARITY_ON_LOW     1
#endif
